CREATE TABLE public.user_genre_score (
	uuid VARCHAR(50),
	action_games INTEGER,
	beat_em_up INTEGER,
	hack_n_slash INTEGER,
	fighting INTEGER,
	platform INTEGER,
	shooter INTEGER,
	survival INTEGER,
	battle_royal INTEGER,
	action_adventure INTEGER,
	stealth INTEGER,
	survival_horror INTEGER,
	adventure INTEGER,
	role_playing INTEGER,
	simulation INTEGER,
	sports INTEGER,
	strategy INTEGER,
	multiplayer_online_battle_arena INTEGER,
	real_time_strategey INTEGER,
	turn_based_strategy INTEGER,
	horror INTEGER,
	massively_multiplayer_online INTEGER,
	puzzle INTEGER,
	PRIMARY KEY (uuid)
)